version: '3'
services:
  client:
    build:
      context: ./client/music-library
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
